---
apiVersion: v1
kind: Secret
metadata:
  namespace: {{ .Values.namespace | default "default" }}
  name: regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
